name: cor
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  auto_size_text: ^3.0.0
  cloud_firestore: ^4.15.6
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.17.5
  firebase_core: ^2.25.4
  firebase_storage: ^11.6.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  get: ^4.6.6
  google_fonts: ^6.1.0
  http: ^1.2.0
  image_picker: ^1.0.7
  path: ^1.9.0
  path_provider: ^2.1.2
  uuid: ^4.3.3

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/logo_icon.svg
    - assets/images/bg_image.svg
