// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_EIgD8a7bfRNDEkUt2ANI6-2egyUrliw',
    appId: '1:27266856527:web:5975f5ebf7ed4906b39c3a',
    messagingSenderId: '27266856527',
    projectId: 'coder-of-rajagiri-4444',
    authDomain: 'coder-of-rajagiri-4444.firebaseapp.com',
    storageBucket: 'coder-of-rajagiri-4444.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcQmVeTY_rw9BFsbtTJF1Bmsl0NNx_4jc',
    appId: '1:27266856527:android:762d43bd329d5e53b39c3a',
    messagingSenderId: '27266856527',
    projectId: 'coder-of-rajagiri-4444',
    storageBucket: 'coder-of-rajagiri-4444.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBupVDlxlN1XZVAwnbJo8qmXIKLQU-40Hk',
    appId: '1:27266856527:ios:e4568823d800a95db39c3a',
    messagingSenderId: '27266856527',
    projectId: 'coder-of-rajagiri-4444',
    storageBucket: 'coder-of-rajagiri-4444.appspot.com',
    iosBundleId: 'com.example.cor',
  );
}
